service: quiztopia-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
    deploymentMethod: direct

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  signup:
    handler: functions/signup/index.handler
    events:
      - http:
          path: /api/quiz/signup
          method: POST
  login:
    handler: functions/login/index.handler
    events:
      - http:
          path: /api/quiz/login
          method: POST
  listQuizzes:
    handler: functions/listQuizzes/index.handler
    events:
      - http:
          path: /api/quiz/quizzes
          method: GET
  getQuizQuestions:
    handler: functions/getQuizQuestions/index.handler
    events:
      - http:
          path: /api/quiz/{quizId}/questions
          method: GET
  createQuiz:
    handler: functions/createQuiz/index.handler
    events:
      - http:
          path: /api/quiz
          method: POST
  addQuestion:
    handler: functions/addQuestion/index.handler
    events:
      - http:
          path: /api/quiz/{quizId}/question
          method: POST
  deleteQuiz:
    handler: functions/deleteQuiz/index.handler
    events:
      - http:
          path: /api/quiz/{quizId}
          method: DELETE
