service: quiztopia-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  signup:
    handler: functions/signup/index.handler
    events:
      - httpApi:
          path: /api/quiz/signup
          method: POST
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: /api/quiz/login
          method: POST
  listQuizzes:
    handler: functions/listQuizzes/index.handler
    events:
      - httpApi:
          path: /api/quiz/quizzes
          method: GET
  getQuizQuestions:
    handler: functions/getQuizQuestions/index.handler
    events:
      - httpApi:
          path: /api/quiz/{quizId}/questions
          method: GET
  createQuiz:
    handler: functions/createQuiz/index.handler
    events:
      - httpApi:
          path: /api/quiz
          method: POST
  addQuestion:
    handler: functions/addQuestion/index.handler
    events:
      - httpApi:
          path: /api/quiz/{quizId}/question
          method: POST
  deleteQuiz:
    handler: functions/deleteQuiz/index.handler
    events:
      - httpApi:
          path: /api/quiz/{quizId}
          method: DELETE
  registerPoints:
    handler: functions/registerPoints/index.handler
    events:
      - httpApi:
          path: /api/quiz/{quizId}/registerPoints
          method: POST
  getTopScores:
    handler: functions/getTopScores/index.handler
    events:
      - httpApi:
          path: /api/quiz/{quizId}/topScores
          method: GET

resources:
  Resources:
    UsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: QuizUsers
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    QuizzesTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: Quizzes
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    LeaderBoardTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: QuizLeaderboard
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: points
            AttributeType: N
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: QuizPointsIndex
            KeySchema:
              - AttributeName: quizId
                KeyType: HASH
              - AttributeName: points
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
